export enum Dependencies {
    AccountService,
    AccountJobService,
    AccountJobScheduleService,
    AccountTokenService,
    AuthService,
    CatalogueService,
    CryptoService,
    JobHelper,
    JobService,
    PlayedTrackService,
    Scheduler,
    SpotifyClient,
    SpotifyMusicProvider,
    UuidSource,
};