export enum Dependencies {
    AccountService,
    AccountJobService,
    AccountJobScheduleService,
    AccountTokenService,
    AlbumService,
    ArtistService,
    AuthService,
    CatalogueService,
    CryptoService,
    PlayedTrackService,
    Scheduler,
    SpotifyClient,
    SpotifyMusicProvider,
    TrackService,
    UuidSource,
};